### ISSUE TITLE
Please Backport also to 1.19.2

### ISSUE THREAD

**Issue by suerion** [TechPro424/Item-Blacklist#1]
Hey, a lot of mods are not supported higher to 1.19.2 our Modpack uses only 1.19.2 some Mod Devs will uppdate there mods to only to 1.20....

Please backport it also to 1.19.2 Thanks

**Comment by TechPro424** [comment]
There is a 1.19.2-compatible build inside the `.zip` file
Can you let me know if this build works on 1.19.2 without any problems?

[itemblacklist-0.0.2-mc1.19.4.zip](https://github.com/TechPro424/Item-Blacklist/files/11239605/itemblacklist-0.0.2-mc1.19.4.zip)

**Comment by suerion** [comment]
Hey, i will look tomorow on this, will try it :)

**Comment by TechPro424** [comment]
@suerion Does it work?

**Comment by suerion** [comment]
Hey, i'm trying this yet. 
1. Completeconfig  version os for 1.19.2 only in 2.1.0, i have changed the dependencies to this version, 
2. Crashed on Joining the Server

[crash-2023-04-21_17.32.13-server.txt](https://github.com/TechPro424/Item-Blacklist/files/11297221/crash-2023-04-21_17.32.13-server.txt)

**Comment by TechPro424** [comment]
@suerion 
It seems like you've loaded a lot of mods, can you try testing if it works with just Fabric API, CompleteConfig, and Item Blacklist installed?

**Comment by suerion** [comment]
Does not work -> Crash on Entity Tick

[crash-2023-04-22_23.25.01-server.txt](https://github.com/TechPro424/Item-Blacklist/files/11302313/crash-2023-04-22_23.25.01-server.txt)

[latest.log](https://github.com/TechPro424/Item-Blacklist/files/11302315/latest.log)

**Comment by TechPro424** [comment]
[itemblacklist-0.0.2-mc1.19.2.zip](https://github.com/TechPro424/Item-Blacklist/files/11307740/itemblacklist-0.0.2-mc1.19.2.zip)

Could you try with this build?

**Comment by suerion** [comment]
You could look on this Vid, without the mods, only with Blacklist, CompleteConfig and API
https://user-images.githubusercontent.com/55131959/234024675-db98d9d9-b37a-4a4d-9db9-be64a4e907d1.mp4

It uses the material, with blocked crafting item

Worked also with the Modpack

**Comment by TechPro424** [comment]
>Worked also with the Modpack

👍

>It uses the material, with blocked crafting item

Yes, that is how it currently works
The material has been used because the blocked item has been crafted
The blocked item is only deleted when a player interacts with it (in this case, when the player places it in their inventory)

Feel free to open a separate issue if you want the recipes of blacklisted items removed as well (though that would mean you would have to reload the server resources using `/reload` each time you update the config)

**Comment by TechPro424** [comment]
@suerion Is this build good enough to release?

**Comment by suerion** [comment]
> @suerion Is this build good enough to release?

Hey, i will come with suggestions for the mod, but i don‘t have a lot of time yet. 

yeah, above you had mentioned to blacklist also the recipes it would be better. Not using the materials would be also good.

I think with the command to add blocks it would be also faster, if we could search with args to add the right item

**Comment by TechPro424** [comment]
> > @suerion Is this build good enough to release?
> 
> Hey, i will come with suggestions for the mod, but i don‘t have a lot of time yet.
> 
> yeah, above you had mentioned to blacklist also the recipes it would be better. Not using the materials would be also good.
> 
> I think with the command to add blocks it would be also faster, if we could search with args to add the right item

So, other than these 2 suggestions, the mod is good to go?

> I think with the command to add blocks it would be also faster, if we could search with args to add the right item

You mean autocomplete item ids?

**Comment by TechPro424** [comment]
https://modrinth.com/mod/item-blacklist/version/0.0.2-mc1.19.2

Released this build

**Comment by suerion** [comment]
Should be done, but add a note in the description, and yeah autocomplete :)

**Comment by TechPro424** [comment]
@suerion could you do some further testing and let me know if I can mark this as a release build instead of alpha?

**Comment by suerion** [comment]
I will come back to you
