### ISSUE TITLE
Permissions system?

### ISSUE THREAD

**Issue by brest21** [TechPro424/Item-Blacklist#4]
I don't see any permissions to disallow players to access the commands to add/remove/list blocks via chat. Not quite sure how to lock players out from being able to just remove the ID from the blacklist.

**Comment by TechPro424** [comment]
🤦‍♂️ 
I'll get to work on fixing it

**Comment by TechPro424** [comment]
Made all the commands op-only
1.19.2: [itemblacklist-0.0.3-mc1.19.2.zip](https://github.com/TechPro424/Item-Blacklist/files/11777998/itemblacklist-0.0.3-mc1.19.2.zip)

Will work on the 1.20 build next


Done: [itemblacklist-0.1.1-mc1.20.zip](https://github.com/TechPro424/Item-Blacklist/files/11778034/itemblacklist-0.1.1-mc1.20.zip)

Test them out and let me know if they're ok

**Comment by TechPro424** [comment]
@brest21 do they work?

**Comment by TechPro424** [comment]
@brest21 

[itemblacklist-0.2.0-mc1.20.zip](https://github.com/TechPro424/Item-Blacklist/files/12096220/itemblacklist-0.2.0-mc1.20.zip)
Try this one out on 1.20 instead

For 1.19.2, try the build I gave earlier

**Comment by TechPro424** [comment]
Fixed by #6
