### ISSUE TITLE
Disable cross dimension

### ISSUE THREAD

**Issue by KimROOOOOGER** [TechPro424/Item-Blacklist#5]
Hey, i want to disable elytra in overworld and nether, and only enable it in End, how would i specify that in the config?

**Comment by TechPro424** [comment]
Per dimension disabling isn't a thing as of now, but it's an interesting idea
Will keep this issue open till I implement it (probably sometime next week, as I'm having exams this week)

**Comment by TechPro424** [comment]
[itemblacklist-0.2.0-mc1.20.zip](https://github.com/TechPro424/Item-Blacklist/files/12096202/itemblacklist-0.2.0-mc1.20.zip)
Try this build out

**Comment by TechPro424** [comment]
@KimROOOOOGER 
[itemblacklist-0.2.0-mc1.20.zip](https://github.com/TechPro424/Item-Blacklist/files/12126630/itemblacklist-0.2.0-mc1.20.zip)
updated build for per dimension blacklist
