### ISSUE TITLE
Blacklist enchantments (Mending)

### ISSUE THREAD

**Issue by 4zy1** [TechPro424/Item-Blacklist#7]
Is there anyway to blacklist enchantments? I'm putting "minecraft:mending" into the config but it doesn't get rid of mending, any help?

**Comment by TechPro424** [comment]
Blacklisting enchantments currently isn't supported, I'll leave this open as a feature that I'll add once 1.20.3 is out and I update to it

**Comment by TechPro424** [comment]
https://modrinth.com/mod/enchantment-disabler
Foudn a mod that does this
