### ISSUE TITLE
Error on restart

### ISSUE THREAD

**Issue by NadarMC** [TechPro424/Item-Blacklist#8]
I have a script that restarts my server every 6 hours or so, I get a funky error when this happens, it seems to be coming from ItemBlackList 0.20-mc1.20. Any clue on how this can be resolved?
![Untitled](https://github.com/TechPro424/Item-Blacklist/assets/160415922/795f9c28-c417-4fee-9cac-f267d011f4de)

This is kinda pressing as I use this mod to disable certain... explosives.. for obvious reasons. As the errors happens on restart, usually when im sleeping, it locks the process until physically exited, thus prevent the new instance from ever booting properly

**Comment by TechPro424** [comment]
Closed as this issue is not caused my this mod
